#!/usr/bin/ansible-playbook -K
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_method: sudo
  tasks:
    - name: Set hostname
      hostname:
        name: satellite1

    - import_tasks: packages.yml

    - name: Setup docker storage
      lineinfile:
        path: /etc/sysconfig/docker-storage-setup
        regexp: '^EXTRA_STORAGE_OPTIONS='
        line: 'EXTRA_STORAGE_OPTIONS="-g /data/docker"'

    - import_tasks: setup.yml
