---
- name: Enable tjuberg/i3-desktop
  command: dnf -y copr enable tjuberg/i3-desktop
  args:
    warn: no

- name: Install list of required packages
  package: name={{ item }} state=installed
  with_items:
    - git
    - tig
    - tmux
    - powerline-fonts
    - fish
    - polybar
    - i3
    - python3-i3ipc
    - dunst
    - rofi
    - network-manager-applet
    - zeal
    - neovim
    - python3-neovim
    - the_silver_searcher
    - python
    - nnn
    - lightdm
    - fish
    - firefox
    - docker
    - flatpak
    - gcc
    - clang
    - cmake
    - spectacle
    - udiskie
    - keychain
    - fzf
    - termite
    - slock
    - pidgin
    - shadow-utils
    - pass
    - ruby
    - php
    - php-json
    - ffmpeg
    - htop
    - clang-tools-extra
    - redshift
    - fontawesome-fonts
    - google-noto-mono-fonts
    - google-noto-sans-fonts
    - google-noto-serif-fonts
    - exa
    - dtrx
    - syncthing
    - fd-find
