---
- name: Enable alebastr/waybar
  command: dnf -y copr enable alebastr/waybar
  args:
    warn: no

- name: install the rpmfusion repo packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_current }}.noarch.rpm
    #sudo dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
    #sudo dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

- name: Install list of required packages
  package: name={{ item }} state=installed
  with_items:
    - git
    - tig
    - tmux
    - powerline-fonts
    - fish
    - sway
    - swaylock
    - swayidle
    - jq
      #- slurp
      #- grim
    - light
    - waybar
    - mako
    - rofi
    - network-manager-applet
    - zeal
    - neovim
    - python3-neovim
    - the_silver_searcher
    - python
    - nnn
    - lightdm
    - fish
    - firefox
    - flatpak
    - pavucontrol
    - podman
    - podman-docker
    - gcc
    - clang
    - cmake
    - make
    - udiskie
    - keychain
    - fzf
    - termite
    - pidgin
    - shadow-utils
    - pass
    - ruby
    - php
    - php-json
    - ffmpeg # For netflix, needs rpmfusion
    - htop
    - clang-tools-extra
    - redshift
    - fontawesome-fonts
      #- google-noto-mono-fonts
    - google-noto-sans-fonts
    - google-noto-serif-fonts
    - exa
      #- dtrx
    - syncthing
    - fd-find
      #- telegram-desktop
    - seafile
