#!/usr/bin/ansible-playbook -K
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_method: sudo
  tasks:
    - name: Set hostname
      hostname:
        name: satellite2

    - import_tasks: packages.yml

    - name: kolabsysvpn
        template:
          src: kolabsysvpn2.networkmanager
          dest: /etc/NetworkManager/system-connections/kolabsys
          owner: root
          group: root
          mode: '0600'

    - import_tasks: setup.yml
