- name: Create the docker group
  group:
    name: docker
    state: present

- name: Setup user mollekopf
  user:
    name: mollekopf
    shell: /bin/fish
    groups: docker, wheel, audio
    append: yes

- name: sudo without password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Disable selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: restart docker
  systemd:
    name: docker
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/mollekopf/.tmux/plugins/tpm

- name: lightdm
  systemd:
    name: lightdm
    enabled: yes

- name: abrtd
  systemd:
    name: abrtd
    enabled: no

- name: arcanist
  command: git clone https://github.com/phacility/arcanist.git  ~/bin/arcanist
  command: git clone https://github.com/phacility/libphutil.git  ~/bin/libphutil

- name: kolabsysvpn
  template:
    src: kolabsysvpn.networkmanager
    dest: /etc/NetworkManager/system-connections/kolabsys
    owner: root
    group: root
    mode: '0600'

- name: reload networkmanager config
  command: nmcli connection reload

- name: abrtd
  systemd:
    name: syncthing
    enabled: yes

- firewalld:
    service: syncthing
    permanent: true
    state: enabled
