- name: Setup user mollekopf
  user:
    name: mollekopf
    shell: /bin/fish
    groups: wheel, audio
    append: yes

- name: sudo without password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Disable selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'

- name: install tpm
  become: true
  become_user: mollekopf
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/mollekopf/.tmux/plugins/tpm
    scope: user

    #- name: lightdm
    #systemd:
    #name: lightdm
    #enabled: yes

- name: abrtd
  systemd:
    name: abrtd
    enabled: no

    #- name: arcanist
    #  command: git clone https://github.com/phacility/arcanist.git  ~/bin/arcanist
    #  command: git clone https://github.com/phacility/libphutil.git  ~/bin/libphutil

- name: reload networkmanager config
  command: nmcli connection reload

- name: syncthing
  become: true
  become_user: mollekopf
  systemd:
    name: syncthing
    enabled: yes
    daemon_reload: yes
    scope: user

- firewalld:
    service: syncthing
    permanent: true
    state: enabled
